
-- 1) roas_mensal unificada
CREATE TABLE public.roas_mensal (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mes date NOT NULL UNIQUE,
  investimento_real numeric,
  investimento_verba_unidades numeric,
  investimento_expansao numeric,
  deals_digital integer,
  deals_expansao integer,
  mrr_medio numeric,
  mrr_total_digital numeric,
  cac numeric,
  cac_recebido numeric,
  roas_direto numeric,
  roas_cac numeric,
  roas_acumulado numeric,
  royalties_mes numeric,
  royalties_acumulado numeric,
  receita_acumulada numeric,
  cpv_medio numeric,
  payback_meses_projetado numeric,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT ON public.roas_mensal TO authenticated;
GRANT ALL ON public.roas_mensal TO service_role;

ALTER TABLE public.roas_mensal ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated read roas_mensal"
  ON public.roas_mensal FOR SELECT
  TO authenticated
  USING (true);

CREATE TRIGGER roas_mensal_updated_at
  BEFORE UPDATE ON public.roas_mensal
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

INSERT INTO public.roas_mensal (
  mes, investimento_real, deals_digital, mrr_medio, cac, roas_direto,
  investimento_verba_unidades, investimento_expansao, deals_expansao,
  mrr_total_digital, cac_recebido, royalties_mes, royalties_acumulado,
  receita_acumulada, cpv_medio, roas_cac, roas_acumulado, payback_meses_projetado
)
SELECT
  COALESCE(m.mes, e.periodo),
  m.investimento, m.deals_digital, m.mrr_medio, m.cac, m.roas_direto,
  COALESCE(e.investimento_verba_unidades, e.investimento_total),
  e.investimento_expansao, e.deals_digitais, e.mrr_total_digital,
  e.cac_recebido, e.royalties_mes, e.royalties_acumulado,
  e.receita_acumulada, e.cpv_medio, e.roas_cac, e.roas_acumulado,
  e.payback_meses_projetado
FROM public.roas_metricas_mensais m
FULL OUTER JOIN public.roas_expansao_mensal e ON e.periodo = m.mes
WHERE COALESCE(m.mes, e.periodo) IS NOT NULL
ON CONFLICT (mes) DO NOTHING;

DROP TABLE public.roas_metricas_mensais;
DROP TABLE public.roas_expansao_mensal;

-- 2) contratos.mrr_mensal
ALTER TABLE public.contratos
  ADD COLUMN mrr_mensal numeric GENERATED ALWAYS AS (mrr / 12) STORED;

-- 3) nps_pesquisas.empresa_id
ALTER TABLE public.nps_pesquisas
  ADD COLUMN empresa_id integer REFERENCES public.empresas(id) ON DELETE SET NULL;

CREATE INDEX idx_nps_pesquisas_empresa_id ON public.nps_pesquisas(empresa_id);

UPDATE public.nps_pesquisas n
SET empresa_id = e.id
FROM public.empresas e
WHERE n.empresa_id IS NULL
  AND n.empresa IS NOT NULL
  AND (
    lower(btrim(e.razao_social)) = lower(btrim(n.empresa))
    OR lower(btrim(e.titulo)) = lower(btrim(n.empresa))
  );
