
-- 1) Estender despesas_cm_fornecedores
ALTER TABLE public.despesas_cm_fornecedores
  ADD COLUMN IF NOT EXISTS mes_inicio smallint CHECK (mes_inicio BETWEEN 1 AND 12),
  ADD COLUMN IF NOT EXISTS parcelas smallint CHECK (parcelas >= 1),
  ADD COLUMN IF NOT EXISTS meses_pontuais smallint[],
  ADD COLUMN IF NOT EXISTS cenario_id uuid REFERENCES public.dre_sim_cenarios(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_despesas_cm_fornecedores_cenario ON public.despesas_cm_fornecedores(cenario_id);

-- 2) Drop simulator tables (empty)
DROP TABLE IF EXISTS public.dre_sim_valores;
DROP TABLE IF EXISTS public.dre_sim_itens;

-- 3) Mirror para receitas
CREATE TABLE IF NOT EXISTS public.receitas_cm_fornecedores (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  categoria text,
  departamento text,
  funcao text,
  tipo text NOT NULL DEFAULT 'fixo',
  valor_base numeric NOT NULL DEFAULT 0,
  rateio_regra text,
  rateio_bu_direto text,
  rateio_custom jsonb,
  ativo boolean NOT NULL DEFAULT true,
  ordem integer,
  mes_inicio smallint CHECK (mes_inicio BETWEEN 1 AND 12),
  parcelas smallint CHECK (parcelas >= 1),
  meses_pontuais smallint[],
  cenario_id uuid REFERENCES public.dre_sim_cenarios(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.receitas_cm_fornecedores TO authenticated;
GRANT ALL ON public.receitas_cm_fornecedores TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.receitas_cm_fornecedores_id_seq TO authenticated;
ALTER TABLE public.receitas_cm_fornecedores ENABLE ROW LEVEL SECURITY;
CREATE POLICY "admins read receitas_cm_fornecedores" ON public.receitas_cm_fornecedores
  FOR SELECT TO authenticated
  USING (has_role(auth.uid(), 'admin'::app_role) OR has_role(auth.uid(), 'diretor'::app_role));
CREATE POLICY "admins all receitas_cm_fornecedores" ON public.receitas_cm_fornecedores
  FOR ALL TO authenticated
  USING (has_role(auth.uid(), 'admin'::app_role) OR has_role(auth.uid(), 'diretor'::app_role))
  WITH CHECK (has_role(auth.uid(), 'admin'::app_role) OR has_role(auth.uid(), 'diretor'::app_role));
CREATE INDEX IF NOT EXISTS idx_receitas_cm_fornecedores_cenario ON public.receitas_cm_fornecedores(cenario_id);
CREATE TRIGGER trg_receitas_cm_fornecedores_updated_at BEFORE UPDATE ON public.receitas_cm_fornecedores
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

CREATE TABLE IF NOT EXISTS public.receitas_cm_overrides (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fornecedor_id bigint NOT NULL REFERENCES public.receitas_cm_fornecedores(id) ON DELETE CASCADE,
  mes date NOT NULL,
  valor numeric,
  inativo_no_mes boolean NOT NULL DEFAULT false,
  status text,
  codigo_omie bigint,
  valor_pago numeric,
  data_pagamento date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(fornecedor_id, mes)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.receitas_cm_overrides TO authenticated;
GRANT ALL ON public.receitas_cm_overrides TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.receitas_cm_overrides_id_seq TO authenticated;
ALTER TABLE public.receitas_cm_overrides ENABLE ROW LEVEL SECURITY;
CREATE POLICY "admins read receitas_cm_overrides" ON public.receitas_cm_overrides
  FOR SELECT TO authenticated
  USING (has_role(auth.uid(), 'admin'::app_role) OR has_role(auth.uid(), 'diretor'::app_role));
CREATE POLICY "admins all receitas_cm_overrides" ON public.receitas_cm_overrides
  FOR ALL TO authenticated
  USING (has_role(auth.uid(), 'admin'::app_role) OR has_role(auth.uid(), 'diretor'::app_role))
  WITH CHECK (has_role(auth.uid(), 'admin'::app_role) OR has_role(auth.uid(), 'diretor'::app_role));
CREATE INDEX IF NOT EXISTS idx_receitas_cm_overrides_fornecedor ON public.receitas_cm_overrides(fornecedor_id);
CREATE TRIGGER trg_receitas_cm_overrides_updated_at BEFORE UPDATE ON public.receitas_cm_overrides
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();
